# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatrix.proto\x12\nmatrixmult\"w\n\rMatrixRequest\x12\x0b\n\x03\x61\x30\x30\x18\x01 \x01(\x05\x12\x0b\n\x03\x61\x30\x31\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x31\x30\x18\x03 \x01(\x05\x12\x0b\n\x03\x61\x31\x31\x18\x04 \x01(\x05\x12\x0b\n\x03\x62\x30\x30\x18\x05 \x01(\x05\x12\x0b\n\x03\x62\x30\x31\x18\x06 \x01(\x05\x12\x0b\n\x03\x62\x31\x30\x18\x07 \x01(\x05\x12\x0b\n\x03\x62\x31\x31\x18\x08 \x01(\x05\"A\n\x0bMatrixReply\x12\x0b\n\x03\x63\x30\x30\x18\x01 \x01(\x05\x12\x0b\n\x03\x63\x30\x31\x18\x02 \x01(\x05\x12\x0b\n\x03\x63\x31\x30\x18\x03 \x01(\x05\x12\x0b\n\x03\x63\x31\x31\x18\x04 \x01(\x05\x32\x98\x01\n\rMatrixService\x12\x45\n\rMultiplyBlock\x12\x19.matrixmult.MatrixRequest\x1a\x17.matrixmult.MatrixReply\"\x00\x12@\n\x08\x41\x64\x64\x42lock\x12\x19.matrixmult.MatrixRequest\x1a\x17.matrixmult.MatrixReply\"\x00\x62\x06proto3')



_MATRIXREQUEST = DESCRIPTOR.message_types_by_name['MatrixRequest']
_MATRIXREPLY = DESCRIPTOR.message_types_by_name['MatrixReply']
MatrixRequest = _reflection.GeneratedProtocolMessageType('MatrixRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATRIXREQUEST,
  '__module__' : 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrixmult.MatrixRequest)
  })
_sym_db.RegisterMessage(MatrixRequest)

MatrixReply = _reflection.GeneratedProtocolMessageType('MatrixReply', (_message.Message,), {
  'DESCRIPTOR' : _MATRIXREPLY,
  '__module__' : 'matrix_pb2'
  # @@protoc_insertion_point(class_scope:matrixmult.MatrixReply)
  })
_sym_db.RegisterMessage(MatrixReply)

_MATRIXSERVICE = DESCRIPTOR.services_by_name['MatrixService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATRIXREQUEST._serialized_start=28
  _MATRIXREQUEST._serialized_end=147
  _MATRIXREPLY._serialized_start=149
  _MATRIXREPLY._serialized_end=214
  _MATRIXSERVICE._serialized_start=217
  _MATRIXSERVICE._serialized_end=369
# @@protoc_insertion_point(module_scope)
